server:
  port: 8082

spring:
  application:
    name: ec-customer-srv
  datasource:
    url: jdbc:postgresql://localhost:5432/taskManager_mbf
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
