server:
  port: 8083
  servlet:
    context-path: /api/customers

spring:
  application:
    name: ec-customer-srv
  datasource:
    url: jdbc:postgresql://localhost:5432/eContract_customer
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always        # kích hoạt khởi tạo SQL
      data-locations: classpath:data.sql  # chỉ định file SQL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
